### ISSUE TITLE
MethodError

### ISSUE THREAD

**Issue by Einste11N** [mzilhao/Jecco.jl#28]
I installed the Jecco package and tried the code given in ./examples/convergence_tests/t10_Nx16.jl, it returned an error after 4 steps while looking for the apparent horizon. The error detail is shown in the attachment files.
It seems that the arguments do not satisfy the data type requirements of OrdinaryDiffEq.BS3Cache. How can I solve this problem? 
Looking forward to your early reply!

![Detail](https://user-images.githubusercontent.com/124479401/216799644-8eed35e6-924c-41b0-91ef-114905cc27b1.png)

**Comment by mzilhao** [comment]
This had already been fixed on the development branch, I believe. I've now merged the changes with the master branch. Can you check again?

**Comment by Einste11N** [comment]
It works properly now. Thank you so much!
